sources:
  - id: "test_cam_1"
    path: "/Users/nurulhudaadamishaq/Downloads/fall1.mp4"
    port: 8081
    location: "ห้องนอน"

  - id: "test_cam_2"
    path: "/Users/nurulhudaadamishaq/Downloads/fall2.mp4"
    port: 8082
    location: "ห้องนั่งเล่น"
  
  - id: "test_cam_3"
    path: "/Users/nurulhudaadamishaq/Downloads/fall3.mp4"
    port: 8083
    location: "ห้องน้ำ"

  - id: "test_cam_4"
    path: "/Users/nurulhudaadamishaq/Downloads/fall4.mp4"
    port: 8084
    location: "ห้องครัว"

  - id: "test_cam_5"
    path: "/Users/nurulhudaadamishaq/Downloads/fall5.mp4"
    port: 8085
    location: "ทางเดิน"

  - id: "test_cam_6"
    path: "/Users/nurulhudaadamishaq/Downloads/trip1.mp4"
    port: 8091
    location: "ทางเดิน"
  
  - id: "test_cam_7"
    path: "/Users/nurulhudaadamishaq/Downloads/trip2.mp4"
    port: 8092
    location: "ทางเดิน"

  - id: "test_cam_8"
    path: "/Users/nurulhudaadamishaq/Downloads/trip3.mp4"
    port: 8093
    location: "ทางเดิน"
  
  - id: "test_cam_9"
    path: "/Users/nurulhudaadamishaq/Downloads/trip4.mp4"
    port: 8094
    location: "ทางเดิน"

  - id: "test_cam_10"
    path: "/Users/nurulhudaadamishaq/Downloads/trip5.mp4"
    port: 8095
    location: "ทางเดิน"

  - id: "test_cam_11"
    path: "/Users/nurulhudaadamishaq/Downloads/walking1.mp4"
    port: 8096
    location: "สนาม"

  - id: "test_cam_12"
    path: "/Users/nurulhudaadamishaq/Downloads/walking2.mp4"
    port: 8097
    location: "สนาม"
