import os
import sys
from pathlib import Path
from dotenv import load_dotenv
import re
import time


class EnvManager:
    REQUIRED_VARS = {
        "MONGODB_URI": "mongodb://localhost:27017",
        "MONGODB_DB_NAME": "sos_system",
        "HELP_WEBHOOK_URL": "",
        "SOS_DB_PATH": "logs/sos_events.db",
        "FORCE_RECORD_ALERTS": "false"
    }

    @staticmethod
    def load_or_create(env_path=".env", require_edit=True):
        """Load .env or create with defaults if missing."""
        env_file = Path(env_path)

        if not env_file.exists():
            print("⚠️  .env not found, creating with defaults...")
            content = "# Auto-generated by system. Edit to configure MongoDB connection.\n"
            for key, default in EnvManager.REQUIRED_VARS.items():
                content += f"{key}={default}\n"
            env_file.write_text(content)
            print(f"✅ Created {env_path}")

            if require_edit:
                print("⏳ Waiting for you to edit .env with your MongoDB connection...")
                mtime_before = env_file.stat().st_mtime
                timeout = 60
                elapsed = 0
                while elapsed < timeout:
                    time.sleep(1)
                    elapsed += 1
                    try:
                        mtime_after = env_file.stat().st_mtime
                        if mtime_after > mtime_before:
                            print("✅ .env file updated, proceeding...")
                            break
                    except:
                        pass
                else:
                    if elapsed >= timeout:
                        print(f"⚠️  Timeout waiting for .env edit (waited {timeout}s)")
                        print("   You can edit .env later and restart")
                        return False

        load_dotenv(env_path)

        # Validate and set defaults for missing vars
        for key, default in EnvManager.REQUIRED_VARS.items():
            val = os.getenv(key)
            if val is None or val == "":
                os.environ[key] = default
                if default:
                    print(f"⚠️  Using default for {key}")

        return True

    @staticmethod
    def validate():
        """Check critical variables."""
        mongodb_uri = os.getenv("MONGODB_URI", "").strip()

        if not mongodb_uri or mongodb_uri == "mongodb://localhost:27017":
            raise RuntimeError(
                "❌ MONGODB_URI not configured in .env\n"
                "   Edit .env with your MongoDB Atlas connection string"
            )

        # Basic format check
        if not mongodb_uri.startswith(("mongodb://", "mongodb+srv://")):
            raise RuntimeError(f"❌ Invalid MONGODB_URI format: {mongodb_uri}")

        return True

    @staticmethod
    def show_config():
        """Display configuration with masked sensitive values."""
        print("\n" + "="*60)
        print("Current Configuration")
        print("="*60)
        for key in EnvManager.REQUIRED_VARS.keys():
            val = os.getenv(key, "")
            if key in ("MONGODB_URI", "HELP_WEBHOOK_URL"):
                display = EnvManager._mask_sensitive(val)
            else:
                display = val
            status = "✓" if val else "✗"
            print(f"{status} {key:25} = {display}")
        print("="*60 + "\n")

    @staticmethod
    def _mask_sensitive(value):
        """Mask sensitive parts of URIs."""
        if not value:
            return "(empty)"
        if "mongodb" in value.lower():
            # Mask password in MongoDB URI
            match = re.search(r"://([^:]+):([^@]+)@", value)
            if match:
                user = match.group(1)
                return f"mongodb+srv://{user}:***@[MASKED]"
            return value[:20] + "..."
        return value[:30] + "..." if len(value) > 30 else value

    @staticmethod
    def get_safe_config():
        """Return configuration dict with masked values for logging."""
        config = {}
        for key in EnvManager.REQUIRED_VARS.keys():
            val = os.getenv(key, "")
            if key in ("MONGODB_URI", "HELP_WEBHOOK_URL") and val:
                config[key] = EnvManager._mask_sensitive(val)
            else:
                config[key] = val
        return config


def init_env(env_path=".env", require_edit=True):
    """Initialize environment - load .env and validate."""
    try:
        EnvManager.load_or_create(env_path, require_edit)
        EnvManager.validate()
        EnvManager.show_config()
        return True
    except Exception as e:
        print(f"❌ Environment initialization failed: {e}")
        return False
